### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by ChristianKrausse** [rogierg/rpi-checkmk#5]
Hi,

I tried to build, after "git clone https://github.com/rogierg/rpi-checkmk" only a subdir "rpi-checkmk" is created, 
the build-command did not work for me. I am a bit confused I thought I have to use docker-compose and need some docker-compose.yml file, is there something missing?
```
/usr/src/checkmk# docker build --no-cache -t rpi-checkmk:latest
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

```

**Comment by scr34my** [comment]
Hi,

you missed the . at the end. I made the same misstake.
