### ISSUE TITLE
Container Exits on Build Image

### ISSUE THREAD

**Issue by dmkw01** [rogierg/rpi-checkmk#7]
I've built an image, but when I run the container using the following command:-

sudo docker run -d --name checkmk -v /opt/omd/sites:/opt/omd/sites -p 5000:5000 rogierg/rpi-checkmk:latest

It exits with Error Code 2

ff88dfb54c40   rpi-checkmk:latest       "/usr/bin/entry.sh s…"   15 seconds ago   Exited (2) 14 seconds ago 

The Docker log file reads:-

            __              __                __              __    
.----.-----.|__|______.----.|  |--.-----.----.|  |--.--------.|  |--.
|   _|  _  ||  |______|  __||     |  -__|  __||    <|        ||    < 
|__| |   __||__|      |____||__|__|_____|____||__|__|__|__|__||__|__|
     |__|     
/app/run.sh: 20: Syntax error: end of file unexpected (expecting "fi")

How can I get this to run correctly?

I'm running Docker on a Raspberry Pi 4B+ with Raspberry Pi OS Lite Bullseye installed.

Thanks.

**Comment by Pitastic** [comment]
Same here !
Just open `run.sh` from this Repo, add a `fi` at the end of the file and rebuild the image.

Unfortunately, this will lead you into the next issue #9

**Comment by rogierg** [comment]
Hi @dmkw01 and @Pitastic sorry for not responding earlier. Quite busy with work. 😊

I need to dive into this a bit. Also I wanted to upgrade to the latest checkmk to fix the vulnerability that was released.

I added the fi for completeness sake to the wrapper script but it seems like checkmk is not added to the image properly.

**Comment by rogierg** [comment]
Hi @dmkw01 and @Pitastic, I've just made a new version that seems to fix this behavior. Fingers crossed! 😊
